// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
	loadDesktopState: () => __TAURI_INVOKE<DesktopBootstrap_Serialize>('load_desktop_state'),
	getRecordingState: () => __TAURI_INVOKE<RecordingState>('get_recording_state'),
	listInputDevices: () => __TAURI_INVOKE<InputDeviceInfo[]>('list_input_devices'),
	pollMicrophoneLevel: () => __TAURI_INVOKE<MicrophoneLevel>('poll_microphone_level'),
	stopMicrophoneLevelMonitor: () => __TAURI_INVOKE<null>('stop_microphone_level_monitor'),
	loadHistory: () => __TAURI_INVOKE<HistoryEntry[]>('load_history'),
	saveHistory: (entries: HistoryEntry[]) =>
		__TAURI_INVOKE<HistoryEntry[]>('save_history', { entries }),
	saveDesktopSettings: (input: DesktopSettingsInput) =>
		__TAURI_INVOKE<DesktopSettings>('save_desktop_settings', { input }),
	revealDesktopSecret: (kind: DesktopSecretKind) =>
		__TAURI_INVOKE<string>('reveal_desktop_secret', { kind }),
	copyDesktopSecret: (kind: DesktopSecretKind) =>
		__TAURI_INVOKE<null>('copy_desktop_secret', { kind }),
	testRemoteConnection: (input: ConnectionInput) =>
		__TAURI_INVOKE<ConnectionReport_Serialize>('test_remote_connection', { input }),
	listOpenrouterModels: () => __TAURI_INVOKE<OpenRouterModelInfo[]>('list_openrouter_models'),
	testOpenrouterKey: (input: OpenRouterConnectionInput) =>
		__TAURI_INVOKE<OpenRouterKeyReport>('test_openrouter_key', { input }),
	listRemoteTokens: () => __TAURI_INVOKE<ApiTokenSummaryDto[]>('list_remote_tokens'),
	/**
	 *  The secret comes back here and nowhere else — the daemon keeps only a hash —
	 *  so the caller has to surface it to the operator before the value is dropped.
	 */
	createRemoteToken: (request: CreateApiTokenRequest) =>
		__TAURI_INVOKE<CreatedApiTokenDto>('create_remote_token', { request }),
	revokeRemoteToken: (name: string) =>
		__TAURI_INVOKE<ApiTokenSummaryDto[]>('revoke_remote_token', { name }),
	refreshRemoteOverview: () => __TAURI_INVOKE<OverviewDto_Serialize>('refresh_remote_overview'),
	updateRemoteRuntime: (runtime: RuntimeConfigDto_Deserialize) =>
		__TAURI_INVOKE<OverviewDto_Serialize>('update_remote_runtime', { runtime }),
	selectRemoteModel: (modelId: string) =>
		__TAURI_INVOKE<OverviewDto_Serialize>('select_remote_model', { modelId }),
	deleteRemoteModel: (modelId: string) =>
		__TAURI_INVOKE<OverviewDto_Serialize>('delete_remote_model', { modelId }),
	startRemoteDownload: (modelId: string) =>
		__TAURI_INVOKE<DownloadJobStatus>('start_remote_download', { modelId }),
	pollRemoteDownload: (jobId: string) =>
		__TAURI_INVOKE<DownloadJobStatus>('poll_remote_download', { jobId }),
	refreshLocalOverview: () => __TAURI_INVOKE<OverviewDto_Serialize>('refresh_local_overview'),
	validateLocalInferencePool: (pool: InferencePoolConfig) =>
		__TAURI_INVOKE<InferencePoolConfig>('validate_local_inference_pool', { pool }),
	preloadLocalModel: () => __TAURI_INVOKE<OverviewDto_Serialize>('preload_local_model'),
	updateLocalRuntime: (runtime: RuntimeConfigDto_Deserialize) =>
		__TAURI_INVOKE<OverviewDto_Serialize>('update_local_runtime', { runtime }),
	selectLocalModel: (modelId: string) =>
		__TAURI_INVOKE<OverviewDto_Serialize>('select_local_model', { modelId }),
	deleteLocalModel: (modelId: string) =>
		__TAURI_INVOKE<OverviewDto_Serialize>('delete_local_model', { modelId }),
	startLocalDownload: (modelId: string) =>
		__TAURI_INVOKE<DownloadJobStatus>('start_local_download', { modelId }),
	pollLocalDownload: (jobId: string) =>
		__TAURI_INVOKE<DownloadJobStatus>('poll_local_download', { jobId }),
	startRecording: () => __TAURI_INVOKE<RecordingStatus>('start_recording'),
	cancelRecording: () => __TAURI_INVOKE<null>('cancel_recording'),
	stopAndTranscribe: () => __TAURI_INVOKE<TranscriptionResult>('stop_and_transcribe')
};

/** Events */
export const events = {
	shadowordDesktopEvent: makeEvent<DesktopEvent>('shadoword://desktop-event')
};

/* Types */
export type ApiTokenRole = 'admin' | 'user';

/**
 *  What an admin is allowed to see about a token that already exists. The stored
 *  hash never leaves the daemon: it is not a secret a client can use, but it is
 *  an offline-guessable one, and nothing here needs it.
 */
export type ApiTokenSummaryDto = {
	name: string;
	role: ApiTokenRole;
};

export type ConnectionInput = {
	endpoint: string;
	token: string | null;
	use_saved_token: boolean;
};

export type ConnectionReport = ConnectionReport_Serialize | ConnectionReport_Deserialize;

export type ConnectionReport_Deserialize = {
	health_ok: boolean;
	status_model_loaded: boolean;
	/**
	 *  `None` when the daemon is old enough to have no version route, which the
	 *  window shows as an unknown version rather than as a failed connection.
	 */
	daemon_version: string | null;
	overview: OverviewDto_Deserialize;
	runtime_config: RuntimeConfigDto_Deserialize;
};

export type ConnectionReport_Serialize = {
	health_ok: boolean;
	status_model_loaded: boolean;
	/**
	 *  `None` when the daemon is old enough to have no version route, which the
	 *  window shows as an unknown version rather than as a failed connection.
	 */
	daemon_version: string | null;
	overview: OverviewDto_Serialize;
	runtime_config: RuntimeConfigDto_Serialize;
};

export type CreateApiTokenRequest = {
	name: string;
	role: ApiTokenRole;
};

/**
 *  The only time the secret is ever transmitted. The daemon keeps a hash, so a
 *  caller that loses this value has to revoke the token and issue another one.
 */
export type CreatedApiTokenDto = {
	name: string;
	role: ApiTokenRole;
	token: string;
};

export type DaemonStatusDto = DaemonStatusDto_Serialize | DaemonStatusDto_Deserialize;

export type DaemonStatusDto_Deserialize = {
	in_flight_requests: number;
	queue_capacity: number;
} & ServiceStatus_Deserialize;

export type DaemonStatusDto_Serialize = {
	in_flight_requests: number;
	queue_capacity: number;
} & ServiceStatus_Serialize;

export type DesktopBootstrap = DesktopBootstrap_Serialize | DesktopBootstrap_Deserialize;

export type DesktopBootstrap_Deserialize = {
	settings: DesktopSettings;
	input_devices: InputDeviceInfo[];
	input_devices_error: string | null;
	recording: RecordingState;
	local_overview: OverviewDto_Deserialize | null;
	local_startup_error: DesktopError | null;
	hotkey_error: string | null;
};

export type DesktopBootstrap_Serialize = {
	settings: DesktopSettings;
	input_devices: InputDeviceInfo[];
	input_devices_error: string | null;
	recording: RecordingState;
	local_overview: OverviewDto_Serialize | null;
	local_startup_error: DesktopError | null;
	hotkey_error: string | null;
};

export type DesktopError = {
	code: string;
	message: string;
	action: string | null;
};

export type DesktopEvent =
	| { type: 'status'; message: string }
	| { type: 'recording_started'; sample_rate: number }
	| { type: 'recording_stopped'; processing: boolean }
	| { type: 'recording_cancelled' }
	| { type: 'transcript_segment'; result: TranscriptionResult; segment_index: number }
	| { type: 'transcription_complete'; result: TranscriptionResult; segments: number }
	| { type: 'error'; code: string; context: string; message: string; action: string | null };

export type DesktopSecretKind = 'remote_token' | 'open_router_key';

export type DesktopSettings = {
	mode: ServiceMode;
	model_path: string;
	preload_on_startup: boolean;
	whisper_accelerator: WhisperAccelerator;
	whisper_gpu_device: number;
	remote_endpoint: string;
	remote_token_configured: boolean;
	openrouter_model: string;
	openrouter_key_configured: boolean;
	input_device: string | null;
	sample_rate: number;
	transcription_mode: TranscriptionMode;
	streaming_pcm_format: StreamingPcmFormat;
	english_only: boolean;
	copy_to_clipboard: boolean;
	paste_method: PasteMethod;
	paste_delay_ms: number;
	output_prefix: TranscriptBoundary;
	output_suffix: TranscriptBoundary;
	hotkey_shortcut: string;
	hotkey_mode: HotkeyMode;
	close_to_tray: boolean;
	show_window_title_bar: boolean;
};

export type DesktopSettingsInput = {
	mode: ServiceMode;
	model_path: string;
	preload_on_startup: boolean;
	whisper_accelerator: WhisperAccelerator;
	whisper_gpu_device: number;
	remote_endpoint: string;
	remote_token: SecretUpdate;
	openrouter_model: string;
	openrouter_key: SecretUpdate;
	input_device: string | null;
	sample_rate: number;
	transcription_mode: TranscriptionMode;
	streaming_pcm_format: StreamingPcmFormat;
	english_only: boolean;
	copy_to_clipboard: boolean;
	paste_method: PasteMethod;
	paste_delay_ms: number;
	output_prefix: TranscriptBoundary;
	output_suffix: TranscriptBoundary;
	hotkey_shortcut: string;
	hotkey_mode: HotkeyMode;
	close_to_tray: boolean;
	show_window_title_bar: boolean;
};

export type DownloadJobState = 'queued' | 'running' | 'succeeded' | 'failed';

export type DownloadJobStatus = {
	id: string;
	model_id: string;
	state: DownloadJobState;
	downloaded: number;
	total: number;
	path: string | null;
	skipped: boolean;
	verified: boolean;
	error: string | null;
};

export type DrainingGenerationStatus = {
	generation: number | null;
	queued_jobs: number;
	queued_audio_bytes: number;
	running_jobs: number;
	running_audio_bytes: number;
	workers_remaining: number;
	loading_units?: number;
};

export type ExecutionTarget =
	| { kind: 'cpu'; threads?: number | null }
	| { kind: 'gpu'; device: number; host_threads?: number | null };

export type ExecutionUnitConfig = {
	id: string;
	enabled?: boolean;
	required?: boolean;
	target: ExecutionTarget;
};

export type ExecutionUnitState = 'unloaded' | 'loading' | 'ready' | 'busy' | 'unhealthy';

export type ExecutionUnitStatus = ExecutionUnitStatus_Serialize | ExecutionUnitStatus_Deserialize;

export type ExecutionUnitStatus_Deserialize = {
	id: string;
	required: boolean;
	target: ExecutionTarget;
	state: ExecutionUnitState;
	last_error?: string | null;
	completed: number | null;
	failed: number | null;
};

export type ExecutionUnitStatus_Serialize = {
	id: string;
	required: boolean;
	target: ExecutionTarget;
	state: ExecutionUnitState;
	last_error?: string | null;
	completed: number | null;
	failed: number | null;
};

/**
 *  Stored raw rather than pre-formatted. The window used to keep history in
 *  memory and could therefore afford a bare `14:32` timestamp — everything on
 *  screen was from the session you were looking at. Once entries outlive the
 *  process that stops being true, so the record carries an absolute instant and
 *  unrounded durations, and the frontend formats them at render.
 */
export type HistoryEntry = {
	id: string;
	/**  RFC 3339, UTC. */
	recorded_at: string;
	mode: ServiceMode;
	engine: string;
	elapsed_ms: number;
	audio_duration_ms: number;
	text: string;
	segments: number;
	cost_usd: number | null;
};

export type HotkeyMode = 'push_to_talk' | 'toggle';

export type InferenceLimits = {
	max_queued_jobs?: number;
	max_queued_audio_bytes?: number;
	max_audio_bytes_per_job?: number;
	max_outstanding_per_flow?: number;
	max_buffered_results_per_flow?: number;
};

export type InferencePoolConfig = {
	units?: ExecutionUnitConfig[];
	limits?: InferenceLimits;
	preload_timeout_ms?: number | null;
	max_draining_generations?: number;
};

export type InferencePoolStatus = InferencePoolStatus_Serialize | InferencePoolStatus_Deserialize;

export type InferencePoolStatus_Deserialize = {
	generation: number | null;
	units: ExecutionUnitStatus_Deserialize[];
	accepting: boolean;
	draining_generations?: DrainingGenerationStatus[];
	ready_units: number;
	busy_units: number;
	unhealthy_units: number;
	queued_jobs: number;
	queued_audio_bytes: number;
	running_jobs: number;
	running_audio_bytes: number;
	completed: number | null;
	failed: number | null;
	last_error?: string | null;
};

export type InferencePoolStatus_Serialize = {
	generation: number | null;
	units: ExecutionUnitStatus_Serialize[];
	accepting: boolean;
	draining_generations: DrainingGenerationStatus[];
	ready_units: number;
	busy_units: number;
	unhealthy_units: number;
	queued_jobs: number;
	queued_audio_bytes: number;
	running_jobs: number;
	running_audio_bytes: number;
	completed: number | null;
	failed: number | null;
	last_error?: string | null;
};

export type InputDeviceInfo = {
	name: string;
	is_default: boolean;
};

export type MicrophoneLevel = {
	/**  Peak normalized sample magnitude since the prior poll, in the range 0.0 to 1.0. */
	peak: number | null;
	/**  False while an active recording exclusively owns the input device. */
	monitoring: boolean;
};

export type ModelInfoDto = {
	id: string;
	name: string;
	filename: string;
	description: string;
	size_bytes: number;
	recommended: boolean;
	installed: boolean;
};

export type ModelStorageDto = {
	directory: string;
	total_bytes: number | null;
	installed_model_count: number;
};

export type OpenRouterConnectionInput = {
	key: string | null;
	use_saved_key: boolean;
};

export type OpenRouterKeyReport = {
	label: string | null;
	is_free_tier: boolean;
	limit: number | null;
	limit_remaining: number | null;
	usage: number | null;
};

export type OpenRouterModelInfo = {
	id: string;
	name: string;
	description: string;
};

export type OverviewDto = OverviewDto_Serialize | OverviewDto_Deserialize;

export type OverviewDto_Deserialize = {
	status: DaemonStatusDto_Deserialize;
	runtime: RuntimeConfigDto_Deserialize;
	models: ModelInfoDto[];
	model_storage?: ModelStorageDto | null;
};

export type OverviewDto_Serialize = {
	status: DaemonStatusDto_Serialize;
	runtime: RuntimeConfigDto_Serialize;
	models: ModelInfoDto[];
	model_storage?: ModelStorageDto | null;
};

export type PasteMethod = 'none' | 'direct' | 'ctrl_v' | 'ctrl_shift_v' | 'shift_insert';

export type RecordingPhase = 'idle' | 'recording' | 'finalizing';

export type RecordingState = {
	phase: RecordingPhase;
	service_mode: ServiceMode | null;
	transcription_mode: TranscriptionMode | null;
	sample_rate: number | null;
	segment_count: number;
};

export type RecordingStatus = {
	recording: boolean;
	sample_rate: number;
};

export type RuntimeConfigDto = RuntimeConfigDto_Serialize | RuntimeConfigDto_Deserialize;

export type RuntimeConfigDto_Deserialize = {
	model_path: string;
	whisper_accelerator: WhisperAccelerator;
	whisper_gpu_device: number;
	english_only: boolean;
	preload_on_startup: boolean;
	inference_pool?: InferencePoolConfig | null;
	/**
	 *  `None` preserves legacy client behavior, while `Some(false)` explicitly
	 *  clears a persisted pool and selects the derived single-unit config.
	 */
	inference_pool_explicit?: boolean | null;
	generation?: number | null;
};

export type RuntimeConfigDto_Serialize = {
	model_path: string;
	whisper_accelerator: WhisperAccelerator;
	whisper_gpu_device: number;
	english_only: boolean;
	preload_on_startup: boolean;
	inference_pool?: InferencePoolConfig | null;
	/**
	 *  `None` preserves legacy client behavior, while `Some(false)` explicitly
	 *  clears a persisted pool and selects the derived single-unit config.
	 */
	inference_pool_explicit?: boolean | null;
	generation?: number | null;
};

export type SecretUpdate =
	{ action: 'keep' } | { action: 'set'; value: string } | { action: 'clear' };

export type ServiceMode = 'local' | 'remote' | 'open_router';

export type ServiceStatus = ServiceStatus_Serialize | ServiceStatus_Deserialize;

export type ServiceStatus_Deserialize = {
	model_loaded: boolean;
	engine: string;
	model_path: string;
	whisper_accelerator: WhisperAccelerator;
	whisper_gpu_device?: number;
	compiled_whisper_backends?: WhisperBackendCapability[];
	available_gpu_devices?: WhisperGpuDeviceInfo[];
	sample_rate: number;
	inference_pool?: InferencePoolStatus_Deserialize | null;
};

export type ServiceStatus_Serialize = {
	model_loaded: boolean;
	engine: string;
	model_path: string;
	whisper_accelerator: WhisperAccelerator;
	whisper_gpu_device: number;
	compiled_whisper_backends: WhisperBackendCapability[];
	available_gpu_devices: WhisperGpuDeviceInfo[];
	sample_rate: number;
	inference_pool?: InferencePoolStatus_Serialize | null;
};

export type StreamingPcmFormat = 's16le' | 'f32le';

export type TranscriptBoundary = 'none' | 'space' | 'newline' | 'blank_line';

export type TranscriptionMode = 'batch' | 'streaming';

export type TranscriptionResult = {
	text: string;
	elapsed_ms: number;
	engine: string;
	audio_duration_ms: number;
	sample_rate: number;
	cost_usd: number | null;
};

export type WhisperAccelerator = 'auto' | 'cpu' | 'gpu';

export type WhisperBackendCapability = 'cpu' | 'vulkan' | 'cuda';

export type WhisperGpuDeviceInfo = {
	id: number;
	name: string;
	kind: WhisperGpuKind;
	total_vram: number;
	free_vram: number;
};

export type WhisperGpuKind = 'dedicated' | 'integrated';

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(
	name: string,
	serialize?: (payload: T) => unknown,
	deserialize?: (payload: any) => T
) {
	const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
		cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
	const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

	const base = {
		listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
		emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
	};

	const fn = (
		target: import('@tauri-apps/api/webview').Webview | import('@tauri-apps/api/window').Window
	) => ({
		listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
		once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
		emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
	});

	return Object.assign(fn, base);
}
